### ISSUE TITLE
Telnet Listener?

### ISSUE THREAD

**Issue by GoremanX** [stuartofmt/DuetLapse3#3]
Would love to have an optional telnet connection that listens for messages from M118 commands issued on the Duet board. Raspbian doesn't have a telnet client installed by default, so this could be implemented through python's telnetlib. This would be great for starting/stopping a timelapse instance by adding M118 gcodes to a printer's profile start/end blocks in slicers. These gcodes are harmless because they don't cause an error if a telnet connection isn't present

**Comment by stuartofmt** [comment]
Lets take these (and future) discussions back onto the Duet Forum so that others can comment / express their wishes / ideas.

My thoughts are that this suggestion is,  in an off itself,  of limited appeal.  There is  a mechanism for starting / stopping based on  pauses in the slicer created gcode.  Personally I don't use it because (in part) of the tendency to get "pause" artifacts on the actual print.  This is the sort of thing that a discussion with others may reveal both utility and appeal.

Having said that - this suggestion (for those that would use it) seems like it would be better approached as a stand alone listener that took telnet need messages and  made http calls to DuetLapse3 instances (running with http listener and hence on a known port).  I believe I probably have all (or most of) the needed actions are already exposed in that manner.  The  original intent of doing so was to facilitate alternative communication / control protocols by having a single abstraction.
