### ISSUE TITLE
[feature request] dark mode support

### ISSUE THREAD

**Issue by modulo1** [stuartofmt/DuetLapse3#37]
I got plugin mode working for DuetLapse3 last night and everything seems to work. Unfortunately the plugin doesn't seem to be aware of the dark mode setting in DWC, resulting in an almost impossible to read status page.

Status page
![image](https://user-images.githubusercontent.com/30335181/229608893-41e20a4b-5859-4bb0-9f01-20c48abb3e15.png)

Info page
![image](https://user-images.githubusercontent.com/30335181/229609123-601d2cae-1944-467a-999b-54b5b517a48a.png)

I found the .css file inside the plugin folder hoping there was an easy edit to resolve but nothing jumped out at me.

Thanks for all your hard work!

~modulo1

**Comment by stuartofmt** [comment]
Yep - I can see that (well not see ...).   Give me a couple of days to see if there is a reasonable fix. I think (?) it may be fairly straightforward to just have the pluging ignore dark mode and use its defined color scheme.  The issue is that there are a couple of levels of redirect involved.  From a quick read, it may also be browser dependent.

**Comment by stuartofmt** [comment]
No problem.  Take a look at  5.2.1 DuetLapse3.zip.

All I did was change a color setting so that it now shows in dark mode.  This will work independent of browser and avoids many complications.  Its not a full dark mode implementation but I think its "good enough" in that its not too offensive :-)

Let me know !

**Comment by modulo1** [comment]
> No problem. Take a look at 5.2.1 DuetLapse3.zip.
> 
> All I did was change a color setting so that it now shows in dark mode. This will work independent of browser and avoids many complications. Its not a full dark mode implementation but I think its "good enough" in that its not too offensive :-)
> 
> Let me know !

Looks great!

![image](https://user-images.githubusercontent.com/30335181/229877731-01099018-05c3-40c4-a13b-042d5dda051a.png)

![image](https://user-images.githubusercontent.com/30335181/229877877-a1568ae1-7f5f-4bc2-a4a1-cec701314b64.png)

**Comment by stuartofmt** [comment]
No further feedback
